admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_login:
    path:     /login
    defaults: { _controller: AdminBundle:Account:login }

admin_logout:
    path:     /logout
    defaults: { _controller: AdminBundle:Account:logout }

admin_users:
    path:     /utilisateurs
    defaults: { _controller: AdminBundle:Default:users }

admin_usersTable:
    path:     /utilisateursTable
    defaults: { _controller: AdminBundle:Default:usersTable }

admin_editUsersRolesModal:
    path:     /editUsersRolesModal/{userId}
    defaults: { _controller: AdminBundle:Default:editUsersRolesModal, userId: null }

admin_userTransactionsHistoryModal:
    path:     /userTransactionsHistoryModal/{userId}
    defaults: { _controller: AdminBundle:Default:userTransactionsHistoryModal, userId: null }

admin_addUserFundsModal:
    path:     /addUserFundsModal/{userId}
    defaults: { _controller: AdminBundle:Default:addUserFundsModal, userId: null }

admin_mediaTypes:
    path:     /mediaTypes
    defaults: { _controller: AdminBundle:Media:getMediaTypesList }

admin_getMediaTypesTable:
    path:     /mediaTypesTable
    defaults: { _controller: AdminBundle:Media:getMediaTypesTable }

admin_editMediaTypeModal:
    path:     /editMediaTypeModal/{mediaTypeId}
    defaults: { _controller: AdminBundle:Media:editMediaTypeModal, mediaTypeId: null }

admin_medias:
    path:     /medias
    defaults: { _controller: AdminBundle:Media:getMediasList }

admin_getMediasTable:
    path:     /mediasTable
    defaults: { _controller: AdminBundle:Media:getMediasTable }

admin_editMediaModal:
    path:     /editMediaModal/{mediaId}
    defaults: { _controller: AdminBundle:Media:editMediaModal, mediaId: null }

admin_mediaGroups:
    path:     /mediaGroups
    defaults: { _controller: AdminBundle:Media:getGroupsList }

admin_getMediaGroupsTable:
    path:     /mediaGroupsTable
    defaults: { _controller: AdminBundle:Media:getGroupsTable }

admin_editMediaGroupModal:
    path:     /editMediaGroupModal/{groupId}
    defaults: { _controller: AdminBundle:Media:editGroupModal, groupId: null }

admin_editMediaGroupsMediasModal:
    path:     /editMediaGroupsMediasModal/{groupId}
    defaults: { _controller: AdminBundle:Media:editGroupMediasModal, groupId: null }

admin_doEditMediaGroupsMediasModal:
    path:     /doEditMediaGroupsMediasModal/{groupId}/{action}/{id}
    defaults: { _controller: AdminBundle:Media:doEditGroupMediasModal, groupId: null, action: null, id: null }