<?php

namespace AppBundle\Repository;

/**
 * MediaGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
