<?php

namespace AppBundle\Repository;

/**
 * MediaGroupsMediasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaGroupsMediasRepository extends \Doctrine\ORM\EntityRepository
{
}
