<?php

namespace AppBundle\Repository;

/**
 * ProfileImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileImageRepository extends \Doctrine\ORM\EntityRepository
{
}
