<?php

namespace AppBundle\Repository;

/**
 * PromoCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
