<?php

namespace AppBundle\Repository;

/**
 * UserTitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTitleRepository extends \Doctrine\ORM\EntityRepository
{
}
