# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    
    role_hierarchy:
        ROLE_ADMIN:         ROLE_PREMIUM
        ROLE_PREMIUM:       ROLE_PAID
        ROLE_PAID:          ROLE_USER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            host: ^%base_host_reg%$
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        register:
            host: ^api\.%base_host_reg%$
            pattern: ^/register
            stateless: true
            anonymous: true

        login:
            host: ^api\.%base_host_reg%$
            pattern:  ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        refresh:
            host: ^api\.%base_host_reg%$
            pattern:  ^/token/refresh
            stateless: true
            anonymous: true

        api:
            host: ^api\.%base_host_reg%$
            pattern:   ^/
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            host: ^%base_host_reg%$
            anonymous: true

    access_control:
        - { host: ^%base_host_reg%$,                                roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: ^api\.%base_host_reg%$, path: ^/register,         roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: ^api\.%base_host_reg%$, path: ^/login,            roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: ^api\.%base_host_reg%$, path: ^/token/refresh,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: ^api\.%base_host_reg%$, path: ^/,                 roles: IS_AUTHENTICATED_FULLY }
