api_default:
    type: rest
    resource: ApiBundle\Controller\DefaultController
    prefix: /

api_user:
    type: rest
    resource: ApiBundle\Controller\UserController
    prefix: /user

api_media:
    type: rest
    resource: ApiBundle\Controller\MediaController
    prefix: /media